module.exports = {
  USERNAME_REQUIRED: 'USERNAME_REQUIRED',
  USERNAME_INVALID: 'USERNAME_INVALID',
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  PASSWORD_INVALID: 'PASSWORD_INVALID',
  CREDENTIALS_INVALID: 'CREDENTIALS_INVALID',
  USER_INACTIVE: 'USER_INACTIVE',
};
